#!/usr/bin/env python
#=========================================================================
# sys-sim [options] elf-binary elf-binary-options
#=========================================================================
#
# This is the simulator for both the functional-level and RTL models of a
# single core and multicore system.
#
#  -h --help            Display this message
#
#  --impl               {fl,base,alt}
#  --trace              Display line tracing
#  --trace-regs         Show regs read/written by each inst
#  --stats              Display statistics
#  --dump-vcd           Dump VCD to sys-<impl>-<elf-binary>.vcd
#  --max-cycles         Set timeout num_cycles, default=1000000
#
#  elf-binary           TinyRV2 elf binary file
#  elf-binary-options   Options to be pased to simulated program
#
# Author : Shunning Jiang, Christopher Batten
# Date   : Oct 2, 2016

# Hack to add project root to python path

import os
import sys
import struct

sim_dir = os.path.dirname( os.path.abspath( __file__ ) )
while sim_dir:
  if os.path.exists( sim_dir + os.path.sep + "pymtl.ini" ):
    sys.path.insert(0,sim_dir)
    break
  sim_dir = os.path.dirname(sim_dir)

import argparse
import re

from pymtl3 import *

from pymtl3.stdlib.stream.ifcs  import IStreamIfc, OStreamIfc
from pymtl3.stdlib.stream       import StreamSourceFL, StreamSinkFL
from pymtl3.stdlib.mem          import MemoryFL, mk_mem_msg, MemMsgType
from pymtl3.stdlib.proc         import SparseMemoryImage, elf_reader
from pymtl3.stdlib.test_utils   import config_model_with_cmdline_opts

from lab2_proc.tinyrv2_encoding import assemble

from lab4_sys.SingleCoreSysFL   import SingleCoreSysFL
from lab4_sys.SingleCoreSys     import SingleCoreSys
from lab4_sys.MultiCoreSysFL    import MultiCoreSysFL
from lab4_sys.MultiCoreSys      import MultiCoreSys

#=========================================================================
# Command line processing
#=========================================================================

class ArgumentParserWithCustomError(argparse.ArgumentParser):
  def error( self, msg = "" ):
    if ( msg ): print("\n ERROR: %s" % msg)
    print("")
    file = open( sys.argv[0] )
    for ( lineno, line ) in enumerate( file ):
      if ( line[0] != '#' ): sys.exit(msg != "")
      if ( (lineno == 2) or (lineno >= 4) ): print( line[1:].rstrip("\n") )

def parse_cmdline():
  p = ArgumentParserWithCustomError( add_help=False )

  # Standard command line arguments

  p.add_argument( "-h", "--help",          action="store_true"   )

  # Additional commane line arguments for the simulator

  p.add_argument( "--impl",  default="score-fl", choices=["score-fl","mcore-fl","base","alt"] )
  p.add_argument( "--trace",               action="store_true"   )
  p.add_argument( "--trace-regs",          action="store_true"   )
  p.add_argument( "--stats",               action="store_true"   )
  p.add_argument( "--dump-vcd",            action="store_true"   )
  p.add_argument( "--max-cycles", default=1000000, type=int      )

  p.add_argument( "elf_file" )

  # We need to figure out which arguments are for the simulator and which
  # arguments are for the simulated program. Note, we cannot juse use
  # parse_known_args alone since bogus arguments before the elf binary
  # would not trigger an error. So we take a two pass approach.

  # First, parse the command line using parse_unused_args so argparse
  # won't complain about the arguments.

  opts,unused = p.parse_known_args()

  # Second, scan through the original argument list, find the elf binary,
  # then collect all remaining arguments so we can load them into the
  # simulated program.

  found_prog = False # set true when found simulated program name
  sim_argv   = []    # arguments for simulator
  prog_argv  = []    # arguments for simulated program

  for arg in sys.argv[1:]:
    if found_prog:
      prog_argv.append(arg)
    elif arg == opts.elf_file:
      sim_argv.append(arg)
      prog_argv.append(arg)
      found_prog = True
    else:
      sim_argv.append(arg)

  # Third, parse the command line again but only passing in the arguments
  # meant for the simulator.

  opts = p.parse_args(sim_argv)

  if opts.help: p.error()
  return opts,prog_argv

#=========================================================================
# Processing Simulated Program Arguments
#=========================================================================
# Takes as input a list of strings representing the arguments we should
# pass to the simulated program and outputs a list of (addr,data) pairs
# suitable for loading into memory. Both the address and data are 4B.
# This is what crt0.S is expecting:
#
#  address
#          -------------------------------------------
#  0xffffc last word in memory
#          -------------------------------------------
#          unusedd until last argument
#          -------------------------------------------
#          arg(argc-1)  : argument argc-1
#          ...
#          arg(1)       : argument 1
#   offset arg(0)       : argument 0
#          -------------------------------------------
#          NULL         : extra null pointer
#          NULL         : end of argument pointers
#          argv[argc-1] : argument pointer argc-1
#          ...
#          argv[1]      : argument pointer 1
#          argv[0]      : argument pointer 0
#  0xff000 argc         : argument count
#          -------------------------------------------

def convert_prog_argv( prog_argv ):

  addr_data = []

  # argc is just the number of program arguments, so let's go ahead and
  # add the corresponding (addr,data) pair

  argc = len(prog_argv)
  addr_data.append(( Bits32(0xff000), Bits32(argc) ))

  # Since we know the number of arguments, we can go ahead and add the
  # two null pointers.

  addr_data.append(( Bits32( 0xff000 + ((argc+1)*4) ), Bits32(0) ))
  addr_data.append(( Bits32( 0xff000 + ((argc+2)*4) ), Bits32(0) ))

  # Figure out the offset shown above. We need one word for argc, one
  # word for the pointer to each argument, and then two words for the
  # NULL pointers. So the offset is (argc+3)*4B

  offset = 0xff000 + ((argc+3)*4)

  # Add the actual argument strings

  for i,arg in enumerate(prog_argv):

    # First set the pointer based on the offset

    addr_data.append(( Bits32( 0xff000 + ((1+i)*4) ), Bits32(offset) ))

    # Add each character in the string, expending the character to 4B

    for c in arg:
      addr_data.append(( Bits32(offset), Bits32(ord(c)) ))
      offset += 4

    # Add final null character

    addr_data.append(( Bits32(offset), Bits32(0) ))
    offset += 4

  # print for debugging

  # for addr,data in sorted(addr_data,reverse=True):
  #   print(addr,data)

  return addr_data

#=========================================================================
# SingleCoreTestHarness
#=========================================================================

class SingleCoreTestHarness( Component ):

  #-----------------------------------------------------------------------
  # constructor
  #-----------------------------------------------------------------------

  def construct( s, Sys ):

    # Interface

    s.proc2mngr     = OStreamIfc( Bits32 )

    s.stats_en      = OutPort()
    s.commit_inst   = OutPort()
    s.icache_access = OutPort()
    s.icache_miss   = OutPort()
    s.dcache_access = OutPort()
    s.dcache_miss   = OutPort()

    # Instantiate source, processor, and memory

    s.src = StreamSourceFL( Bits32, [] )
    s.sys = Sys()
    s.mem = MemoryFL(2, mem_ifc_dtypes=[mk_mem_msg(8,32,128),mk_mem_msg(8,32,128)] )

    # System <-> Proc/Mngr

    # Note simulator only gets output, so we don't need to worry about
    # the mngr2proc interface. We just hook it up to an empty stream
    # source.

    s.src.ostream //= s.sys.mngr2proc

    # The simulator will monitor the proc2mngr interface at the top level
    # for handling various message types.

    s.proc2mngr //= s.sys.proc2mngr

    # System <-> Memory

    s.sys.imem //= s.mem.ifc[0]
    s.sys.dmem //= s.mem.ifc[1]

    # Bring the stats enable up to the top level

    s.stats_en      //= s.sys.stats_en
    s.commit_inst   //= s.sys.commit_inst
    s.icache_access //= s.sys.icache_access
    s.icache_miss   //= s.sys.icache_miss
    s.dcache_access //= s.sys.dcache_access
    s.dcache_miss   //= s.sys.dcache_miss

  #-----------------------------------------------------------------------
  # load memory image
  #-----------------------------------------------------------------------

  def load( self, mem_image ):
    sections = mem_image.get_sections()
    for section in sections:
      start_addr = section.addr
      stop_addr  = section.addr + len(section.data)
      self.mem.mem.mem[start_addr:stop_addr] = section.data

  #-----------------------------------------------------------------------
  # cleanup
  #-----------------------------------------------------------------------

  def cleanup( s ):
    del s.mem.mem[:]

  #-----------------------------------------------------------------------
  # line trace
  #-----------------------------------------------------------------------

  def line_trace( s ):

    imem_reqstr = "  "
    if s.mem.ifc[0].reqstream.val and s.mem.ifc[0].reqstream.rdy:
      imem_reqstr = MemMsgType.str[int(s.mem.ifc[0].reqstream.msg.type_)]

    imem_respstr = "  "
    if s.mem.ifc[0].respstream.val and s.mem.ifc[0].respstream.rdy:
      imem_respstr = MemMsgType.str[int(s.mem.ifc[0].respstream.msg.type_)]

    imem_str = "     "
    if imem_reqstr != "  " or imem_respstr != "  ":
      imem_str = f"{imem_reqstr}>{imem_respstr}"

    dmem_reqstr = "  "
    if s.mem.ifc[1].reqstream.val and s.mem.ifc[1].reqstream.rdy:
      dmem_reqstr = MemMsgType.str[int(s.mem.ifc[1].reqstream.msg.type_)]

    dmem_respstr = "  "
    if s.mem.ifc[1].respstream.val and s.mem.ifc[1].respstream.rdy:
      dmem_respstr = MemMsgType.str[int(s.mem.ifc[1].respstream.msg.type_)]

    dmem_str = "     "
    if dmem_reqstr != "  " or dmem_respstr != "  ":
      dmem_str = f"{dmem_reqstr}>{dmem_respstr}"

    mem_str = f"{imem_str}|{dmem_str}"

    return ("*" if s.sys.stats_en else " ") + \
           s.sys.line_trace() + " " + \
           mem_str

#=========================================================================
# MultiCoreTestHarness
#=========================================================================

class MultiCoreTestHarness(Component):

  #-----------------------------------------------------------------------
  # constructor
  #-----------------------------------------------------------------------

  def construct( s, Sys ):

    # Interface

    s.proc2mngr     = OStreamIfc( Bits32 )

    s.stats_en      = OutPort()
    s.commit_inst   = OutPort()
    s.icache_access = OutPort()
    s.icache_miss   = OutPort()
    s.dcache_access = OutPort()
    s.dcache_miss   = OutPort()

    # Instantiate source, processor, and memory

    s.srcs  = [ StreamSourceFL( Bits32, [] ) for _ in range(4) ]
    s.sinks = [ StreamSinkFL( Bits32, [] )   for _ in range(4) ]
    s.sys   = Sys()
    s.mem   = MemoryFL(2, mem_ifc_dtypes=[mk_mem_msg(8,32,128),mk_mem_msg(8,32,128)] )

    # Processor <-> Proc/Mngr

    # Note simulator only gets output, so we don't need to worry about
    # the mngr2proc interface. We just hook all of the mngr2proc
    # interfaces up to empty stream sources.

    for i in range(4):
      s.srcs[i].ostream //= s.sys.mngr2proc[i]

    # The simulator will only monitor the proc2mngr interface for core 0
    # at the top level for handling various message types. So we hook up
    # the proc2mngr interfaces for the other cores up to empty stream
    # sources.

    s.proc2mngr //= s.sys.proc2mngr[0]
    for i in range(1,4):
      s.sys.proc2mngr[i] //= s.sinks[i].istream

    # System <-> Memory

    s.sys.imem //= s.mem.ifc[0]
    s.sys.dmem //= s.mem.ifc[1]

    # Bring the stats enable up to the top level

    s.stats_en      //= s.sys.stats_en
    s.commit_inst   //= s.sys.commit_inst
    s.icache_access //= 0
    s.icache_miss   //= 0
    s.dcache_access //= 0
    s.dcache_miss   //= 0

  #-----------------------------------------------------------------------
  # load
  #-----------------------------------------------------------------------

  def load( self, mem_image ):
    sections = mem_image.get_sections()
    for section in sections:
      start_addr = section.addr
      stop_addr  = section.addr + len(section.data)
      self.mem.mem.mem[start_addr:stop_addr] = section.data

  #-----------------------------------------------------------------------
  # cleanup
  #-----------------------------------------------------------------------

  def cleanup( s ):
    del s.mem.mem[:]

  #-----------------------------------------------------------------------
  # done
  #-----------------------------------------------------------------------

  def done( s ):
    for i in range(4):
      if not s.srcs[i].done() or not s.sinks[i].done():
        return False
    return True

  #-----------------------------------------------------------------------
  # line_trace
  #-----------------------------------------------------------------------

  def line_trace( s ):

    imem_reqstr = "  "
    if s.mem.ifc[0].reqstream.val and s.mem.ifc[0].reqstream.rdy:
      imem_reqstr = MemMsgType.str[int(s.mem.ifc[0].reqstream.msg.type_)]

    imem_respstr = "  "
    if s.mem.ifc[0].respstream.val and s.mem.ifc[0].respstream.rdy:
      imem_respstr = MemMsgType.str[int(s.mem.ifc[0].respstream.msg.type_)]

    imem_str = "     "
    if imem_reqstr != "  " or imem_respstr != "  ":
      imem_str = f"{imem_reqstr}>{imem_respstr}"

    dmem_reqstr = "  "
    if s.mem.ifc[1].reqstream.val and s.mem.ifc[1].reqstream.rdy:
      dmem_reqstr = MemMsgType.str[int(s.mem.ifc[1].reqstream.msg.type_)]

    dmem_respstr = "  "
    if s.mem.ifc[1].respstream.val and s.mem.ifc[1].respstream.rdy:
      dmem_respstr = MemMsgType.str[int(s.mem.ifc[1].respstream.msg.type_)]

    dmem_str = "     "
    if dmem_reqstr != "  " or dmem_respstr != "  ":
      dmem_str = f"{dmem_reqstr}>{dmem_respstr}"

    mem_str = f"{imem_str}|{dmem_str}"

    return ("*" if s.sys.stats_en else " ") + \
           s.sys.line_trace() + " " + \
           mem_str

#=========================================================================
# Main
#=========================================================================

def main():

  # Parse commandline, opts are the options for the simulator, while
  # prog_argv are the arguments for the simulated program

  opts,prog_argv = parse_cmdline()

  # Open elf binary

  mem_image = None
  with open(opts.elf_file,'rb') as file_obj:
    mem_image = elf_reader( file_obj )

  # Create test harness

  if opts.impl == "score-fl":
    th = SingleCoreTestHarness( SingleCoreSysFL )
  elif opts.impl == "mcore-fl":
    th = MultiCoreTestHarness( MultiCoreSysFL )
  elif opts.impl == "base":
    th = SingleCoreTestHarness( SingleCoreSys )
  elif opts.impl == "alt":
    th = MultiCoreTestHarness( MultiCoreSys )

  # Create VCD filename

  unique_name = ""
  if opts.dump_vcd:
    elf_file_basename = os.path.basename( opts.elf_file )
    unique_name = f"sys-sim-score-{elf_file_basename}.vcd"

  cmdline_opts = {
    'dump_vcd': f"{unique_name}" if opts.dump_vcd else '',
  }

  # Trace registers

  if opts.trace_regs:
    th.set_param( "top.proc.construct", trace_regs=True )

  # Configure the test harness component

  config_model_with_cmdline_opts( th, cmdline_opts, duts=['sys'] )

  # Apply necessary passes

  th.apply( DefaultPassGroup( linetrace=opts.trace ) )

  # Load the program into the model

  th.load( mem_image )

  # Load the arguments

  prog_argv_addr_data = convert_prog_argv(prog_argv)

  for addr,data in prog_argv_addr_data:
    th.mem.write_mem( addr, struct.pack('i',data.uint()) )

  # Stats

  num_cycles        = 0
  num_commit_inst   = 0
  num_icache_access = 0
  num_icache_miss   = 0
  num_dcache_access = 0
  num_dcache_miss   = 0

  # Storage for print

  wprint      = False
  wprint_type = None  # 0: int, 1: char, 2: string

  # Reset test harness

  if opts.trace:
    print()
  th.sim_reset()

  # We are always ready to accept a proc2mngr message

  th.proc2mngr.rdy @= 1

  # Run the simulation

  while th.sim_cycle_count() < opts.max_cycles:

    # Update cycle count

    if th.stats_en:
      num_cycles += 1

      if th.commit_inst:   num_commit_inst   += 1
      if th.icache_access: num_icache_access += 1
      if th.icache_miss:   num_icache_miss   += 1
      if th.dcache_access: num_dcache_access += 1
      if th.dcache_miss:   num_dcache_miss   += 1

    # Check the proc2mngr interface

    if th.proc2mngr.val:

      msg_type = th.proc2mngr.msg[16:32]
      msg_xtra = th.proc2mngr.msg[ 0:16]

      # Check if we are doing a wprint

      if wprint:

        # Print int

        if wprint_type == 0:
          print( th.proc2mngr.msg[:].uint(), end='' )
          wprint = False

        # Print character

        if wprint_type == 1:
          print( chr(th.proc2mngr.msg[:].uint()), end='' )
          if chr(th.proc2mngr.msg[:].uint()) == '\n':
            sys.stdout.flush()
          wprint = False

        # Print string

        if wprint_type == 2:
          char_as_num = th.proc2mngr.msg[:].uint()
          if char_as_num > 0:
            print( chr(char_as_num), end='' )
          else:
            wprint = False

      # exit message

      elif msg_type == 1:
        if opts.trace:
          th.print_line_trace()
        if ( msg_xtra.uint() != 0 ):
          exit( msg_xtra.uint() )
        else:
          break

      # wprint message

      elif msg_type == 3:

        if msg_xtra == 3:
          sys.stdout.flush()
        else:
          wprint = True
          wprint_type = msg_xtra

        if wprint_type not in [0,1,2,3]:
          if opts.trace:
            th.print_line_trace()
          print("ERROR: received unrecognized app print type!")
          exit(1)

    # Tick the simulator

    th.sim_tick()

  # Force a test failure if we timed out

  if th.sim_cycle_count() >= opts.max_cycles:
    print(f"""
   ERROR: Exceeded maximum number of cycles ({opts.max_cycles}). Your
   application might be in an infinite loop, or you need to use the
   --max-cycles command line option to increase the limit.
    """)
    exit(1)

  # Extra ticks to make VCD easier to read

  if opts.trace:
    th.print_line_trace()
  th.sim_tick()
  th.sim_tick()
  th.sim_tick()

  # Stats

  if opts.stats:
    if num_commit_inst == 0:
      print("""
    ERROR: stats were never enabled in the program. You need to
    use ece4750_stats_on() and ece4750_stats_off()
     """)
    else:

      cpi = 0.0
      if num_commit_inst > 0:
        cpi = float(num_cycles) / float(num_commit_inst)

      icache_miss_rate = 0.0
      if num_icache_access > 0:
        icache_miss_rate = float(num_icache_miss) / float(num_icache_access)

      dcache_miss_rate = 0.0
      if num_dcache_access > 0:
        dcache_miss_rate = float(num_dcache_miss) / float(num_dcache_access)

      print()
      print( f" num_cycles        = {num_cycles}" )
      print( f" num_inst          = {num_commit_inst}" )
      print( f" CPI               = {cpi:1.2f}" )
      print()
      print( f" num_icache_access = {num_icache_access} " )
      print( f" num_icache_miss   = {num_icache_miss} " )
      print( f" icache_miss_rate  = {icache_miss_rate:1.2f} " )
      print()
      print( f" num_dcache_access = {num_dcache_access} " )
      print( f" num_dcache_miss   = {num_dcache_miss} " )
      print( f" dcache_miss_rate  = {dcache_miss_rate:1.2f} " )
      print()

main()

